<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>..\build\GameServer\$(Configuration)\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <AssemblyName>GameServer</AssemblyName>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <IntermediateOutputPath>..\build\GameServer\$(Configuration)\obj\</IntermediateOutputPath>
    <OutputPath>..\build\GameServer\$(Configuration)\lib\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>Dawn of Light - GameServer</AssemblyTitle>
    <Description>Library containing server side emulating framework</Description>
    <Copyright>Dawn of Light Development Team</Copyright>
    <Company>Dawn of Light Development Team</Company>
    <Product>DAoC Server Side Emulation Package - Dawn of Light</Product>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>Full</DebugType>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>False</Optimize>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>None</DebugType>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>True</Optimize>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Platform)' == 'AnyCPU' ">
    <RegisterForComInterop>False</RegisterForComInterop>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.19.4" />
    <PackageReference Include="Grpc" Version="2.43.0" />
    <PackageReference Include="log4net" Version="2.0.13" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
    <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="2.0.226801" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="6.0.0" />
    <ProjectReference Include="..\DOLBase\DOLBase.csproj" Name="DOLBase" />
    <ProjectReference Include="..\DOLDatabase\DOLDatabase.csproj" Name="DOLDatabase" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\GameServer\**\*.cs" />
    <Compile Remove="..\..\GameServer\gameutils\DOLScriptCompiler.cs" />
    <EmbeddedResource Include="..\..\GameServer\config\*" />
    <TranslationFiles Include="..\..\GameServer\language\**\*.txt" />
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\AbortQuestGoal.cs">
      <Link>quests\JsonQuests\Goals\AbortQuestGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\CollectGoal.cs">
      <Link>quests\JsonQuests\Goals\CollectGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\DataQuestJsonGoal.cs">
      <Link>quests\JsonQuests\Goals\DataQuestJsonGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\DummyGoal.cs">
      <Link>quests\JsonQuests\Goals\DummyGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\EndGoal.cs">
      <Link>quests\JsonQuests\Goals\EndGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\EnterAreaGoal.cs">
      <Link>quests\JsonQuests\Goals\EnterAreaGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\InteractGoal.cs">
      <Link>quests\JsonQuests\Goals\InteractGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\KilledGoal.cs">
      <Link>quests\JsonQuests\Goals\KilledGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\KillGoal.cs">
      <Link>quests\JsonQuests\Goals\KillGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\StopGoal.cs">
      <Link>quests\JsonQuests\Goals\StopGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\TimerGoal.cs">
      <Link>quests\JsonQuests\Goals\TimerGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\UseItemGoal.cs">
      <Link>quests\JsonQuests\Goals\UseItemGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\Goals\WhisperGoal.cs">
      <Link>quests\JsonQuests\Goals\WhisperGoal.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\DataQuestJson.cs">
      <Link>quests\JsonQuests\DataQuestJson.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\DataQuestJsonMgr.cs">
      <Link>quests\JsonQuests\DataQuestJsonMgr.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\DBDataQuestJson.cs">
      <Link>quests\JsonQuests\DBDataQuestJson.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\GMQuestCommand.cs">
      <Link>quests\JsonQuests\GMQuestCommand.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\PlayerQuest.cs">
      <Link>quests\JsonQuests\PlayerQuest.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\core\IEnumerableExts.cs">
      <Link>core\CollectionExts.cs</Link>
    </Compile>
    <Compile Update="..\..\GameServer\quests\JsonQuests\IQuest.cs">
      <Link>quests\JsonQuests\IQuest.cs</Link>
    </Compile>
  </ItemGroup>
  <Target Name="CopyFiles" AfterTargets="AfterBuild">
    <Copy SourceFiles="@(TranslationFiles)" DestinationFiles="@(TranslationFiles->'$(MSBuildProjectDirectory)\..\$(Configuration)\languages\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
